### ISSUE TITLE
Please consider publishing to Maven Central

### ISSUE THREAD

**Issue by alexeyr** [JohnReedLOL/scala-trace-debug#20]
It isn't a problem for a library to add `resolvers += "johnreed2 bintray" at "http://dl.bintray.com/content/johnreed2/maven"` (by the way, isn't the equivalent needed for Maven as well)? It is a bit worse to require everyone who depends on this library to add it too. I was thinking how I could avoid this problem, but can't find a reliable way :( Though SBT does allow to make this dependency for SNAPSHOT versions only.

See https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html and https://blog.bintray.com/2014/02/11/bintray-as-pain-free-gateway-to-maven-central/ for explanation how to upload from Bintray to Maven Central.

**Comment by JohnReedLOL** [comment]
I had no idea someone else depended on this library, lol. I have other things to do now, but if it isn't too much trouble I'll do it.

---

Side note: I'm thinking of redoing this to make the variables names shorter:

Debug.trace("Foo")                      --> Err("Foo")
Debug.traceStdOut("Foo")           --> Out("Foo")

SDebug.traceCode("Foo")            -->  ErrCode("Foo")
SDebug.traceCodeStdOut("Foo") -->  OutCode("Foo")

Debug.check(1 == 1)                     -->  Check(1 == 1)
Debug.checkStdOut(1 == 1)          -->  CheckOut(1 == 1)

Debug.assrt(1 == 1)                       -->  Assert(1 == 1)
Debug.assertStdOut(1 == 1)          -->  AssertOut(1 == 1)
- For convenience, assertions will always print out whatever failed ex. `(1 == 1) -> true`.
- `Err.apply("Foo")` and `Out.apply("Foo")` should work in Java.
- Implicit conversions will be renamed to make them shorter.

**Comment by alexeyr** [comment]
Well, we don't, because of this issue :) Though your library is mentioned at https://github.com/typesafehub/scala-logging, so I wouldn't be surprised if people do depend on it.

For main work project we probably won't, because we are trying to reduce the dependencies, we'll probably just have our own macros adapted to our requirements. But for my personal projects, I would avoid having my own version as well.

Also a side note: would you object if I used `scala.trace` group ID for https://github.com/alexeyr/scala-trace-entry-exit?

**Comment by JohnReedLOL** [comment]
One thing you have to keep in mind is that I'm actually a junior dev and this is my first "real" published repo, so you'll have to bear with me.

 > Also a side note: would you object if I used scala.trace group ID

If it in any way prevents me from getting that group ID in OSS or whatever than no, but if you just want to start you package names with same prefix as me, that is fine as long as it doesn't affect me.

I made this Sonotype OSS thing way back, but I found it to be inconvenient so I just stuck with BinTray...

https://issues.sonatype.org/browse/OSSRH-21413

On https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html it says I need a "Maven Central User token key and User token password". I don't even know how to make a Maven Central account much less find token-key/password. I have never used the "mvn" command before.

Keep in mind that I am 22, starting my first paid coding job and that this is all new to me. 

By the way - having an annotation to produce a clickable stack trace for every method call would be so useful for debugging. Instead of clicking "step over" in a debugger, I could just press "Ctr-Alt-Down" and jump from method call to method call, tracking program flow in my head. I don't know if type annotations could be smart enough to do something like this:

@out def foo(a: Int, b: Int): Int = {...} // print to standard out
@err def foo(a: Int, b: Int): Int = {...} // print to standard error

object global { 
    val logger = new Logger("MyLogger") // logger is in static object scope
}

@log(logger) def foo(a: Int, b: Int): Int = {...} // print to logger

    ran method foo at path.to.foo(Foo:23)

Getting the actual values of the parameters would be a big plus for primitive types.

    ran foo(1, 2): 3 at path.to.foo(Foo:23)

Although for non-primitive types this could be ugly

    ran foo([I@18df8434, [I@25aca718): [I@2c177f9e at path.to.foo(Foo:23)

It would be nicer to output 

    ran foo(Array[Int], Array[Int]): Array[Int] at path.to.foo(Foo:23)

**Comment by JohnReedLOL** [comment]
That's fine.

**Comment by JohnReedLOL** [comment]
@alexeyr Can you help me out? In "[bintray](https://bintray.com/johnreed2/maven/scala-trace-debug#central)" it says

> "Developer information missing Missing Signature: '/com/github/johnreedlol/scala-trace-debug_2.10/3.0.0/scala-trace-debug_2.10-3.0.0-sources.jar.asc' does not exist for 'scala-trace-debug_2.10-3.0.0-sources.jar'"

**Comment by alexeyr** [comment]
Have you set up signing as described in https://blog.bintray.com/2013/08/06/fight-crime-with-gpg/?

**Comment by timcharper** [comment]
@JohnReedLOL it isn't too difficult; the worst part is getting a maven central org setup.

Start here:

http://central.sonatype.org/pages/producers.html#individual-projects-open-source-software-repository-hosting-ossrh

Once done, I could help you with updating your build.sbt et al

**Comment by JohnReedLOL** [comment]
@timcharper I'll try to get Scala-Trace-Debug set up at https://issues.sonatype.org/browse/OSSRH-21413 by this weekend.

**Comment by JohnReedLOL** [comment]
@alexeyr @timcharper Hey guys, I am really close. I uploaded to bintray and got the gpg keys set up in the 4.0 branch. Calling "publish-signed" with the sbt-pgp plugin generates [this pom file](https://drive.google.com/file/d/0B1IimJ20gG0SemVUMWxhUnM2V2s/view?usp=sharing), but when I try to sync from bintray to maven central, I get [this error message](https://drive.google.com/file/d/0B1IimJ20gG0SbWdBUjNRUTVDYVE/view?usp=sharing).

**Comment by JohnReedLOL** [comment]
Success! https://drive.google.com/file/d/0B1IimJ20gG0SVWdnRDM1R1N0Y2s/view?usp=sharing
